on:
  push:
    branches: [master]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Remove release
        uses: cb80/delrel@latest
        with:
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Latest
          body: |
            Latest build that uses a hosted broadcaster
          draft: false
          prerelease: false
      - name: Build dist.zip
        working-directory: ./canvas
        run: |
          npm ci
          npm run build
          zip -r dist.zip dist
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_CONTROLLER_URL: https://lyrx.dev/living_space/controller
          VITE_SYNC_SERVER_URL: ws://living-space-broadcaster.lyrx.dev
          VITE_DEBUG_INFO: false
          VITE_ASSERTS: false
          VITE_DEBUG_VISUAL: false
          VITE_CONSTANT_TIME_S: 0
          VITE_COUNT_START_CREATURES: 50
          VITE_QR: false
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip
